nodejs_version: "14.x"
xorg_conf: xorg.nvidia.conf.j2
channel_name: intlprotests
stream_width: 1920
stream_height: 1080
stream_delay: 30
stream_bitrate: 5500
stream_x264_preset: "faster"
stream_x264_psy_tune: "film"
stream_nvenc_preset: "hq"
grid_count: 6
streamdelay_in_uri: "srt://127.0.0.1:5000?mode=caller"
streamdelay_out_uri: "srt://127.0.0.1:5001?mode=listener"
streamdelay_hostname: "localhost"
streamdelay_port: 8404
streamdelay_encoder: "nvenc"
streamcapture_out_uri: "srt://:5000?mode=listener"
streamcapture_bitrate: 9000
streamcapture_x264_preset: "ultrafast"
streamcapture_nvenc_preset: "hq"
streamcapture_encoder: "nvenc"
rtmpoutput_in_uri: "srt://127.0.0.1:5001?mode=caller"
streamwall_control_address: "https://{{ inventory_hostname }}"
streamwall_control_hostname: "localhost"
streamwall_control_port: 8000
streamwall_announce_username: "internationalbot"
streamwall_announce_color: "#ff0000"
streamwall_announce_template: "SingsMic Active Feed: <%- stream.source %> <%- stream.city && stream.state ? `(${stream.city} ${stream.state})` : '' %> <%- stream.link %>"
streamwall_announce_interval: 120
streamwall_announce_delay: 30

streamwall_cpu_affinity: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
streamcapture_cpu_affinity: "16,17,18,19"
streamcapture_x264_threads: 8
streamdelay_cpu_affinity: "20,21,22,23"
streamdelay_x264_threads: 8

netdata_bind_to: { "127.0.0.1" }