---
- name: Set timezone to America/Los_Angeles
  timezone:
    name: America/Los_Angeles

- name: Create streamwall user
  user:
    name: streamwall
    home: /home/streamwall
    shell: /bin/bash

- name: Create systemd user service directory
  file:
    path: "{{ user_service_dir }}"
    state: directory
    owner: streamwall
    group: streamwall

- name: Setup X server
  include: xserver.yml
  tags: xserver

- name: Setup streamcapture
  include: streamcapture.yml
  tags: streamcapture

- name: Setup streamwall
  include: streamwall.yml
  tags: streamwall

- name: Setup streamdelay
  include: streamdelay.yml
  tags: streamdelay

- name: Setup rtmp outputs
  include: rtmpoutput.yml
  tags: rtmpoutput

- name: Setup stream content
  include: content.yml
  tags: content

- name: Setup caddy
  include: caddy.yml
  tags: caddy

- name: Setup vnc
  include: vnc.yml
  tags: vnc

- name: Add stream target service file
  copy:
    src: stream.target
    dest: "{{ user_service_dir }}/stream.target"
    owner: streamwall
    group: streamwall
  notify:
    - Reload user systemd
    - Start stream
